### ISSUE TITLE
pathlib module not found

### ISSUE THREAD

**Issue by knanne** [ElsevierDev/elsapy#11]
Installing python 3.6 with Anaconda includes [pathlib2](https://pypi.python.org/pypi/pathlib2/) instead of [pathlib](https://pypi.python.org/pypi/pathlib/), which then throws an error when importing `elsclient`  

Is it worth looking into replace this library, or doing something like the following:  

```python
try:
    import pathlib
except ImportError:
    import pathlib2 as pathlib
```

**Comment by ale-de-vries** [comment]
Thanks for the tip. Adjusted in latest commit (version 0.4.2.)
