### ISSUE TITLE
errors while running the code

### ISSUE THREAD

**Issue by alejandro-aragon** [ElsevierDev/elsapy#13]
I'm trying the Python script, and though I have a valid API key, I get errors:

`

$ python exampleProg.py 
Read author failed.
Read affiliation failed.
Read document failed.
pii_doc.title:  Establishing the fair allocation of international aviation carbon emission rights 
doi_doc.title:  Sensitive Sequencing Method for KRAS Mutation Detection by Pyrosequencing 
Load documents (Y/N)?
--> Y
Read docs for author failed.
Read docs for affiliation failed.
Traceback (most recent call last):
  File "exampleProg.py", line 87, in <module>
    auth_srch.execute(client)
  File "/Users/aaragon/Local/elsapy/elsapy/elssearch.py", line 79, in execute
    api_response = els_client.exec_request(self._uri)
  File "/Users/aaragon/Local/elsapy/elsapy/elsclient.py", line 117, in exec_request
    raise requests.HTTPError("HTTP " + str(r.status_code) + " Error from " + URL + "\nand using headers " + str(headers) + ":\n" + r.text)
requests.exceptions.HTTPError: HTTP 500 Error from https://api.elsevier.com/content/search/author?query=authlast(keuskamp)
and using headers {'X-ELS-APIKey': '[edited_out]', 'User-Agent': 'elsapy-v0.3.2', 'Accept': 'application/json'}:
{"service-error":{"status":{"statusCode":"GENERAL_SYSTEM_ERROR","statusText":"Unrecoverable service exception occurred"}}}`

Anyone knows why I'm getting these problems? Should I try with an older version of the code?

**Comment by sacrophyte** [comment]
Ditto - looking at the code, the example program checks my_auth.read(client), but doesn't really go into any details about what the error is.

**Comment by ale-de-vries** [comment]
It seems this is caused by a deprecated URL syntax used in the SDK . We are working to fix this and will update the repository hopefully within a few days.

**Comment by sacrophyte** [comment]
Yup, this did the trick for me. Thanks for the quick turn around!

**Comment by chunnanhsu** [comment]
I got exactly the same error like the above. I have a valid API key but no inst_token, so I just commented that line for reading inst_token. I put "http://www.ucsd.edu" as my Website URL to get API key. Please help. Thank you!
