### ISSUE TITLE
query error

### ISSUE THREAD

**Issue by sacrophyte** [ElsevierDev/elsapy#14]
Good day,

I have a list of names I wish to iterate through to gather author profiles, but I seem to have constructed the query incorrectly. Unfortunately, after reading the various documentations, it is not clear to me what exactly is wrong with the query. Would you be able to provide any insight?

**my.py**
`fnames=[]
lnames=[]
with open('authors.txt','r') as f:
    reader=csv.reader(f,delimiter='\t')
    for fname,lname in reader:
        fnames.append(fname)
        lnames.append(lname) 

numNames=len(fnames)
print ("Imported ", numNames, " names")
    
con_file = open("config.json")
config = json.load(con_file)
con_file.close()

client = ElsClient(config['apikey'])
client.inst_token = config['insttoken']

for i in range(numNames):
    query='AUTHOR-NAME(AUTHLASTNAME('+lnames[i]+') AUTHFIRST('+fnames[i]+')) AND AFFIL("University of Illinois" OR "University of Illinois at Urbana-Champaign"'
    print ("Searching: ", query)
    auth_srch = ElsSearch(query,'author')
    auth_srch.execute(client)
    print ("auth_srch has", len(auth_srch.results), "results.")`

and the error:

`(C:\Users\sac\AppData\Local\Continuum\Anaconda3\envs\scopus) C:\Users\sac\scopus_project\elsapy>python my.py
Imported  533  names
Searching:  AUTHOR-NAME(AUTHLASTNAME(Endres) AUTHFIRST(A Bryan)) AND AFFIL("University of Illinois" OR "University of Illinois at Urbana-Champaign"
Traceback (most recent call last):
  File "my.py", line 62, in <module>
    auth_srch.execute(client)
  File "C:\Users\sac\scopus_project\elsapy\elsapy\elssearch.py", line 75, in execute
    api_response = els_client.exec_request(self._uri)
  File "C:\Users\sac\scopus_project\elsapy\elsapy\elsclient.py", line 119, in exec_request
    raise requests.HTTPError("HTTP " + str(r.status_code) + " Error from " + URL + "\nand using headers " + str(headers) + ":\n" + r.text)
requests.exceptions.HTTPError: HTTP 400 Error from https://api.elsevier.com/content/search/author?query=AUTHOR-NAME(AUTHLASTNAME(Endres) AUTHFIRST(A Bryan)) AND AFFIL("University of Illinois" OR "University of Illinois at Urbana-Champaign"
and using headers {'X-ELS-APIKey': 'xxxxxxxxxxxxxxxxxxxxxxx', 'User-Agent': 'elsapy-v0.4.2', 'Accept': 'application/json'}:
{"service-error":{"status":{"statusCode":"INVALID_INPUT","statusText":"Unable to translate query provided."}}}`

**Comment by sacrophyte** [comment]
I see that my query is missing a closing parenthesis (after the last string). However, that is not the root problem - if I only use AUTHOR-NAME, apparently the query breaks due to the space between AUTHLASTNAME and AUTHFIRST, even though both individual queries work (I experimented with an encoded space as well (%20):

`Searching:  AUTHLASTNAME(Endres)
auth_srch has 25 results.
Searching:  AUTHFIRST(A Bryan)
auth_srch has 25 results.
Searching:  AUTHOR-NAME(AUTHLASTNAME(Endres)%20AUTHFIRST(A Bryan))
Traceback (most recent call last):
  File "my.py", line 48, in <module>
    getAuthors(query)
  File "my.py", line 36, in getAuthors
    auth_srch.execute(client)
  File "C:\Users\sac\scopus_project\elsapy\elsapy\elssearch.py", line 75, in execute
    api_response = els_client.exec_request(self._uri)
  File "C:\Users\sac\scopus_project\elsapy\elsapy\elsclient.py", line 119, in exec_request
    raise requests.HTTPError("HTTP " + str(r.status_code) + " Error from " + URL + "\nand using headers " + str(headers) + ":\n" + r.text)
requests.exceptions.HTTPError: HTTP 400 Error from https://api.elsevier.com/content/search/author?query=AUTHOR-NAME(AUTHLASTNAME(Endres)%20AUTHFIRST(A Bryan))
and using headers {'X-ELS-APIKey': 'xxxxxxxxxxxxxxxxxx', 'User-Agent': 'elsapy-v0.4.2', 'Accept': 'application/json'}:
{"service-error":{"status":{"statusCode":"INVALID_INPUT","statusText":"Unable to translate query provided."}}}`

Seems to be the same syntax used in the documentation:
[http://api.elsevier.com/content/search/fields/scopus]

**Comment by sacrophyte** [comment]
Also tried url-encoding (as suggested by http://api.elsevier.com/documentation/search/SCOPUSSearchTips.htm), but still get errors:

import urllib.parse

def getAuthors( query ):
   "Get the profile of an author"
   print ("Searching: ", query)

   auth_srch = ElsSearch(urllib.parse.quote_plus(query),'author')
   auth_srch.execute(client)
   print ("auth_srch has", len(auth_srch.results), "results.")
   return

query='AUTHLASTNAME(Endres)'
getAuthors(query)

query='AUTHFIRST(A Bryan)'
getAuthors(query)

query='AUTHOR-NAME(AUTHLASTNAME(Endres) AUTHFIRST(A Bryan))'
getAuthors(query)


Searching:  AUTHLASTNAME(Endres)
auth_srch has 25 results.
Searching:  AUTHFIRST(A Bryan)
auth_srch has 25 results.
Searching:  AUTHOR-NAME(AUTHLASTNAME(Endres) AUTHFIRST(A Bryan))
Traceback (most recent call last):
  File "my.py", line 50, in <module>
    getAuthors(query)
  File "my.py", line 38, in getAuthors
    auth_srch.execute(client)
  File "C:\Users\sac\scopus_project\elsapy\elsapy\elssearch.py", line 75, in execute
    api_response = els_client.exec_request(self._uri)
  File "C:\Users\sac\scopus_project\elsapy\elsapy\elsclient.py", line 119, in exec_request
    raise requests.HTTPError("HTTP " + str(r.status_code) + " Error from " + URL + "\nand using headers " + str(headers) + ":\n" + r.text)
requests.exceptions.HTTPError: HTTP 400 Error from https://api.elsevier.com/content/search/author?query=AUTHOR-NAME%28AUTHLASTNAME%28Endres%29+AUTHFIR
ST%28A+Bryan%29%29
and using headers {'X-ELS-APIKey': 'xxxxxxxxxxxxxxxxx', 'User-Agent': 'elsapy-v0.4.2', 'Accept': 'application/json'}:
{"service-error":{"status":{"statusCode":"INVALID_INPUT","statusText":"Unable to translate query provided."}}}

**Comment by sacrophyte** [comment]
Through further experimentation, it appears that AUTHOR-NAME is not supported. Very odd.

**Comment by ale-de-vries** [comment]
Apologies for the late reply. It seems that you are trying to do a search against the AUTHOR index (i.e. the index that returns a list of authors), but are using syntax that is only supported by Scopus document search (index: 'SCOPUS', which returns a list of documents). In other words: there is a difference between searching for documents by a certain author (which is what you would use the 'SCOPUS' index for, with the syntax you included here), and searching for authors (which is what you would use the 'AUTHOR' index for. See [here](https://dev.elsevier.com/tips/AuthorSearchTips.htm) for the fields and syntax supported by the AUTHOR index.
