### ISSUE TITLE
Enhancement request: provide a wrapper for the Scopus Analyzer API

### ISSUE THREAD

**Issue by sacrophyte** [ElsevierDev/elsapy#16]
Good day (again)! :)

Do you have any plans to write a python wrapper for the Scopus Analyzer API? For example:
https://www.scopus.com/term/analyzer.uri?src=s&sort=plf-f&sdt=cite&sot=cite&sl=18&citedAuthorId=55698719300

I would like to retrieve a year-by-year count for a list of authors. Unfortunately, I have not been able to find where the Analyzer API is even documented, so I am not exactly sure where to begin.

Hope all is well,

**Comment by ale-de-vries** [comment]
Apologies for the late reply (again :) )

The 'search analyzer' you point to is actually just another way of representing search results - specifically, using facets. See https://api.elsevier.com/documentation/ScopusSearchAPI.wadl, and look for 'facets'.
