### ISSUE TITLE
Parsing resources, include protocol to response resources. 

### ISSUE THREAD

**Issue by cuent** [ElsevierDev/elsapy#17]
I am querying some information about authors and the URIs aren't correctly parsed. To develop further, making the next call to the API:

`http://api.elsevier.com/content/author/author_id/AUTHOR_ID:57193429229?apiKey=##############&view=ENHANCED&httpAccept=application/rdf%2Bxml`

Returns all resources with domain `api.elsevier.com` without a protocol. An example of a resource is `://api.elsevier.com/content/serial/title/issn/21945357`

For now, I am parsing and correcting each URI while reading the RDF with Sesame Rio. But it would be great if this is fixed from the provider.

**Comment by ale-de-vries** [comment]
Thanks, submitted as a bug to development.

**Comment by cuent** [comment]
The last updates of the API, resources come with the protocol.

Before:

`://api.elsevier.com/content/author/author_id/6506281895`

Now:

`https://api.elsevier.com/content/author/author_id/6506281895`
