### ISSUE TITLE
Retrieve index keywords

### ISSUE THREAD

**Issue by alfredocarella** [ElsevierDev/elsapy#18]
I am using this module to automatically perform a simple Scopus search and save some article metadata (basically keywords), which I then analyze to look for correlations.

If I do a manual search from the website and export its results, I am able to select two fields called "Author Keywords" and "Index Keywords" for each record. When I use the API, however, the field "Index Keywords" appears to be missing even when I am adding the parameter `&view=COMPLETE` (see minimum working example below). Is there a way to get the full metadata for the search results? 
```
## Import modules
from elsapy.elsclient import ElsClient
from elsapy.elssearch import ElsSearch
import json

## Load configuration
with open("config.json") as con_file:
    config = json.load(con_file)  # Only my API key in this file
client = ElsClient(config['apikey'])
    
## Define query and execute search
query = 'PUBYEAR > 2015 AND TITLE-ABS-KEY(Masonry+Earthquake)&view=COMPLETE'
doc_srch = ElsSearch(query, 'scopus')
doc_srch.execute(client, get_all=False)

## Print obtained fields for the first record
print(doc_srch.results[0].keys())
>>>dict_keys(['@_fa', 'link', 'prism:url', 'dc:identifier', 'eid', 'dc:title', 'dc:creator', 'prism:publicationName', 'prism:issn', 'prism:volume', 'prism:pageRange', 'prism:coverDate', 'prism:coverDisplayDate', 'prism:doi', 'pii', 'dc:description', 'citedby-count', 'affiliation', 'prism:aggregationType', 'subtype', 'subtypeDescription', 'author-count', 'author', 'authkeywords', 'source-id'])
```
I have double-checked that:
1. The field "Index Keywords" exists and contains information that I can export using the manual search.
2. This data is not included when I retrieve the same records using the API.

**Comment by ale-de-vries** [comment]
Apologies for the late reply. Index Keywords are not by default available through the API - this is by design. If you need these index keywords for non-commercial research purposes, you can contact us through https://dev.elsevier.com to request permission.
