### ISSUE TITLE
Problem searching by subject classification

### ISSUE THREAD

**Issue by JosephWYoung** [ElsevierDev/elsapy#19]
I am trying to use ElsSearch to retrieve DOI's for documents classified by subject area. 
The query 
```python
 subj_srch = ElsSearch(word + '+SUBJAREA(' + subj + ')','scidir')
 subj_srch.execute(client)
```

(where `subj` varies from "AGRI" to "BIOC", for example) does not yield unique results. If I remove the word query, I get an error. How can I search by subject classification?

**Comment by m-direnzo** [comment]
Hello Joseph,

Apologies for the delayed response.

Regarding your query, the subject area classifications for the ScienceDirect Search API differ from those used with the Scopus Search API.  "AGRI" and "BIOC" will only work with Scopus; for ScienceDirect, you would use "agribio" and "biochemgenmolbiol", respectively.

Please see the ScienceDirect Search API documentation here:
- https://api.elsevier.com/documentation/ScienceDirectSearchAPI.wadl
and the valid subject classifications here:
- https://api.elsevier.com/content/subject/scidir?httpAccept=text/xml

I hope that helps!

Best regards,
Matthew DiRenzo

**Comment by JosephWYoung** [comment]
Thank you Matthew! 
This is very helpful. 

I am also encountering problems interacting with the ElsAuthor class.
The read_docs() method always seems to return False, and the read_metrics method always returns AttributeError: 'NoneType' object has no attribute 'exec_request'.

However, when I visit an author's profile, there are very frequently bios and several documents under their name.

Are author metrics and document lists only available for a small sample of authors or am I going about things incorrectly?

Thanks again,

Joseph
