### ISSUE TITLE
Unable to run the exampleProg.py... 

### ISSUE THREAD

**Issue by chunnanhsu** [ElsevierDev/elsapy#23]
This appears to say that my APIkey is not good? Any hint? Thank you!

$ python3 exampleProg.py
Read author failed.
Read affiliation failed.
scp_doc.title:  Control of somatic tissue differentiation by the long non-coding RNA TINCR
pii_doc.title:  Establishing the fair allocation of international aviation carbon emission rights
doi_doc.title:  Sensitive Sequencing Method for KRAS Mutation Detection by Pyrosequencing
Load documents (Y/N)?
--> Y
Read docs for author failed.
Read docs for affiliation failed.
Traceback (most recent call last):
  File "exampleProg.py", line 89, in <module>
    auth_srch.execute(client)
  File "/home/chunnan/ElsaPy/elsapy/elsapy/elssearch.py", line 75, in execute
    api_response = els_client.exec_request(self._uri)
  File "/home/chunnan/ElsaPy/elsapy/elsapy/elsclient.py", line 119, in exec_request
    raise requests.HTTPError("HTTP " + str(r.status_code) + " Error from " + URL + "\nand using headers " + str(headers) + ":\n" + r.text)
requests.exceptions.HTTPError: HTTP 401 Error from https://api.elsevier.com/content/search/author?query=authlast(keuskamp)
and using headers {'Accept': 'application/json', 'User-Agent': 'elsapy-v0.4.6', 'X-ELS-APIKey': '[edited-out]'}:
{"service-error":{"status":{"statusCode":"AUTHORIZATION_ERROR","statusText":"The requestor is not authorized to access the requested view or fields of the resource"}}}

**Comment by ma-ji** [comment]
Try to use an authorized IP address to make the request.

**Comment by ale-de-vries** [comment]
Authorization errors can be caused for a number of reasons. See [here](https://dev.elsevier.com/tecdoc_article_access.html) for a full overview.

**Comment by mpasternak** [comment]
It still happens. Authorized IP or not. 

Documentation @ale-de-vries linked is pretty vague on this topic. Just as the returned error messages from API server. 

Is contacting support the preferred way to handle such failures? 

```
b'{"service-error":{"status":{"statusCode":"AUTHORIZATION_ERROR","statusText":"The requestor is not authorized to access the requested view or fields of the resource"}}}'
```

**Comment by mpasternak** [comment]
Possible duplicate here
#68

**Comment by phdsmhong** [comment]
I received the same error ... maybe because I did not provide insttoken?

**Comment by mpasternak** [comment]
You need to run it from your institution computer ip.

**Comment by phdsmhong** [comment]
> You need to run it from your institution computer ip.

Did using institution IP solve the issue above? Thank you in advance!

**Comment by mpasternak** [comment]
For me it did. Pity it's nowhere clearly documented in Elsevier's docs.
