### ISSUE TITLE
Error getting citation info for REFEID

### ISSUE THREAD

**Issue by dfajt** [ElsevierDev/elsapy#25]
Hi.
I'm trying to get citation info for REFEID (https://api.elsevier.com/content/search/scopus?apiKey=xxx&view=COMPLETE&httpAccept=application/json&suppressNavLinks=true&query=REFEID(2-s2.0-84864329732)&field=eid,prism:coverDate&date=2018)

I have hidden my apiKey.
I'm getting error:
{"service-error":{"status":{"statusCode":"INVALID_INPUT","statusText":"Use of certain field restrictions in the search query is not allowed for this requestor."}}}
I think my organization (Slovenian IZUM) doesn't have such restrictions. What can I do to obtain this data?

Sincerely,
Dejan Fajt
Developer
IZUM - Slovenia

**Comment by ale-de-vries** [comment]
Apologies for the late response - we're clearing out old issues.

REFEID is a restricted field. Clients based at organizations that have a Scopus subscription can request this field to be made available to them by contacting us through https://dev.elsevier.com.
