### ISSUE TITLE
Subject Area Information from ElsSearch

### ISSUE THREAD

**Issue by nmor487** [ElsevierDev/elsapy#27]
Hey there,

I'm currently constructing an ElsSearch for multiple papers using their EIDs. While I can retrieve almost all the information, such as: authors, affiliations, etc. I cannot receive data on a papers subject area. My current code for the search is:

ElsSearch('EID(2-s2.0-0000001493) OR EID(2-s2.0-0000000118) &view=COMPLETE','scopus')

**Comment by ale-de-vries** [comment]
Apologies for the really late response - working through issue backlog.

Subject areas are not included in Scopus document search results. However, each search result has a URI (e.g. https://api.elsevier.com/content/abstract/scopus_id/0037070197) that points the corresponding Scopus record, which does have subject area information (see [here](https://dev.elsevier.com/payloads/retrieval/abstractRetrievalResp.xml) for an example). You can use this URI to create an instance of the `AbsDoc' class in elsapy and access the document that way.
