### ISSUE TITLE
How to download science direct files in XML format rather than json?

### ISSUE THREAD

**Issue by PawanKaur** [ElsevierDev/elsapy#29]
Hello,

So I want to download the  science direct full article files in XML than default JSON from your API. Though, I did tried to change the elsentity.py  write function to download it in XML but it gives me blank file with an error message; 
TypeError: must be str, not dict

How can  I fix this and get data in XML? I can see that it is possible to do that through your interactive API:

https://dev.elsevier.com/sciencedirect.html#!/Article_Retrieval/ArticleRetrieval_0_1

I need to do so is because I need only portion of the text and data from Materials and Methods section. This is possible only by extracting tags from XML as in JSON all is in description tag.

Hope to receive your help soon.

**Comment by leeyongze** [comment]
i only used the search moduel to get doi, then ,use library requests get xml file.
how do you solve this problem？

**Comment by ale-de-vries** [comment]
elsapy doesn't currently support XML responses. @leeyongze's is a valid workaround: use the search module to get the DOI (or PII), then use a generic HTTP request library (such as `requests`) to retrieve the documents in XML format. Also refer to https://dev.elsevier.com/documentation/ArticleRetrievalAPI.wadl for information about the request syntax.

**Comment by sj2812** [comment]
https://shivani-jadhav2812.medium.com/scidirect-research-papers-as-xml-files-6f96c2b59ce8 refer to this link

**Comment by tohidarehman1988** [comment]
> Hello,
> 
> So I want to download the science direct full article files in XML than default JSON from your API. Though, I did tried to change the elsentity.py write function to download it in XML but it gives me blank file with an error message;
> TypeError: must be str, not dict
> 
> How can I fix this and get data in XML? I can see that it is possible to do that through your interactive API:
> 
> https://dev.elsevier.com/sciencedirect.html#!/Article_Retrieval/ArticleRetrieval_0_1
> 
> I need to do so is because I need only portion of the text and data from Materials and Methods section. This is possible only by extracting tags from XML as in JSON all is in description tag.
> 
> Hope to receive your help soon.

At the time of xml format full paper downloading, is it downloading the research highlights also or not?
Please help me in this regard

**Comment by sj2812** [comment]
XML Format full paper downloading should download the highlights as well

**Comment by tohidarehman1988** [comment]
> XML Format full paper downloading should download the highlights as well

Yes, that's been true, But I have tried a lot and unable to download highlights.
It is downloading full paper in XML format, excluding "author_highlights".
Can you please check once that it is doing or not.
Thanks in advance.

**Comment by tohidarehman1988** [comment]
Dear sir/Madam
I am trying a lot of downloading full paper in xml. It is downloading full
paper, but author written highlights part is missing.
Can you please help me to download the dataset of full paper with research
highlights.
Thank you so much in advance.
