### ISSUE TITLE
Search results questions

### ISSUE THREAD

**Issue by diehlpk** [ElsevierDev/elsapy#31]
While searching for some keywords, I realized that I always got 5k
results. Is the the limitation for results per query? It is quite strange that for several keywords, I got always 5k results.

The follow up questions is are the 5k results from the most recent ones going back in year? Or randomly chosen?

**Comment by rogerrohrbach** [comment]
The maximum number of results requested is[ hard-coded](https://github.com/ElsevierDev/elsapy/blob/a8a8b043816441e3ed0c834e792f7089231092da/elsapy/elssearch.py#L79) to 5,000.  Lest you think you can get around this, it's enforced in the API as well.

**Comment by pmsoltani** [comment]
Is there any way of using pagination? i.e. retrieving 25 results at a time and moving forward?

**Comment by ale-de-vries** [comment]
We have implemented a feature on the Scopus search REST endpoint that supports pagination beyond the first 5,000 results - see 'cursor' under 'query params' on https://dev.elsevier.com/documentation/ScopusSearchAPI.wadl. This feature has not been adopted by elsapy yet.
