### ISSUE TITLE
Question about university token 

### ISSUE THREAD

**Issue by diallobakary4** [ElsevierDev/elsapy#34]
I did loggin into elsevier using my university account then created an API key which I added in
https://github.com/ElsevierDev/elsapy/blob/master/CONFIG.md.
But I did not receive a university token. Will the API key be sufficient to retrieve Full Text papers available only through the university account?

**Comment by ale-de-vries** [comment]
You can retrieve full-text papers using your APIkey without an institutional token, as long as you are within the IP range of your institution. If you are not, and you wish to request off-network access to your university's subscribed content, contact us through https://dev.elsevier.com

**Comment by SusBioRes-UBC** [comment]
Hi @ale-de-vries, I'm having the same issue (working from home via university VPN). I sent a request to (integrationsupport@elsevier.com) to set up an institutional token a few days ago, but no response so far. Is there another way to request an institutional token? I tried to find a different email from https://dev.elsevier.com, but no luck.
Thank you!
