### ISSUE TITLE
Author doc_list

### ISSUE THREAD

**Issue by rwprkr** [ElsevierDev/elsapy#37]
I'm trying to retrieve doc lists by author ID. I'm able to establish the connection, read data (so I can get full name, etc), but after running read_docs the doc_list returns as None. I've tried it with authors that I know, as well as the example from the wiki and all return None. It doesn't throw an error, just returns None.

e.g.
myAuth = ElsAuthor(author_id="7202909704")
myAuth.read_docs(my_client)
print(myAuth.doc_list, type(myAuth.doc_list))
>> None <class 'NoneType'>

**Comment by ale-de-vries** [comment]
the read_docs method requires elevated permissions for your APIkey - apologies that this is not clear (will add that to documentation). Please contact us through https://dev.elsevier.com to request elevated permissions.
