### ISSUE TITLE
An explanation of what to do with the files?

### ISSUE THREAD

**Issue by MiG-25Altfuns** [ElsevierDev/elsapy#9]
Hi there,

I'm rather new to programming and completely new to GitHub. I didn't really understand what I was supposed to do with the elsapy files on GitHub and went on to waste a lot of time trying to use pip, and trying to understand what people normally do on GitHub (which has nothing to do with me). 

Perhaps a brief explanation of how the files are supposed to work may save hassle at both ends?

I've barely started (but at least I don't get a 'No Module elsapy'!)... so you may still hear from me...xD

Thank you for the git and thank you in advance for any further help!

Cheers,

Alfonso

**Comment by ale-de-vries** [comment]
Thanks for the feedback, Alfonso - much appreciated. Getting elsapy onto your local machine isn't really any different than from any other GitHub repository: either you clone it using git, or you download it as a ZIP file. You then need to either include the cloned/unzipped elsapy folder in your project folder or add it to your standard Python package path (see https://docs.python.org/3/tutorial/modules.html#the-module-search-path for more details). Having said that - we made that a bit more explicit in the 'Quick Start' section of elsapy's README.
